In [1]:
import numpy as np

# 创建数组
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [2]:
# 创建多维数组
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr1.dtype

dtype('float64')

In [4]:
arr2.dtype

dtype('int32')

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
np.empty((2,3,2))

array([[[7.81975925e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 3.09059538e-057]],

       [[6.38853480e-067, 6.70373671e+170],
        [1.77427963e+160, 1.20014003e-071],
        [9.95657583e-043, 1.61604227e+160]]])

In [8]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr = np.array([1,2,3], dtype=np.float64)
arr.dtype

dtype('float64')

In [11]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [12]:
# 使用astype显式转换dtype
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [13]:
int_array = np.arange(10)
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [15]:
# 数组与标量的运算
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [17]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [19]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [20]:
# 基本的索引和切片
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[5]

5

In [22]:
arr[0]

0

In [23]:
arr[5:8]

array([5, 6, 7])

In [25]:
arr[5:8] = 12 # 当你将一个标量值赋给一个切片时，该值会自动传播到整个选区

In [26]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [27]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [28]:
arr_slice[1] = 12345

In [29]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [31]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [33]:
# 二维数组的索引
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [34]:
arr2d[0][2]

3

In [36]:
arr2d[0,2]

3

In [38]:
# 多维数组的索引
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
arr3d[1,0]

array([7, 8, 9])

In [43]:
# 切片索引
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [44]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr2d[:2] # 行

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr2d[:2,:1] # 先行后列

array([[1],
       [4]])

In [47]:
arr2d[1,:2]

array([4, 5])

In [48]:
arr2d[2,:1]

array([7])

In [49]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [50]:
arr2d[:2,:1]=0
arr2d

array([[0, 2, 3],
       [0, 5, 6],
       [7, 8, 9]])

In [54]:
# 布尔型索引
names = np.array(['Bob', 'Joe', 'Will','Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)

In [56]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [53]:
data

array([[-4.04752381e-01,  1.48577247e-01,  2.60036705e-01,
         1.83113407e-01],
       [ 2.91414238e-01, -5.27897731e-02, -9.89632360e-01,
        -4.45266806e-01],
       [-2.10845536e-01,  1.59630687e+00, -1.93137361e+00,
        -1.33464019e-02],
       [ 1.57698733e+00,  1.70844556e+00,  1.79518671e+00,
        -6.12727146e-01],
       [-1.08655963e+00, -2.48025166e+00, -7.29006024e-01,
        -1.55330376e+00],
       [-1.70306034e-01, -3.42739568e-01, -3.52455094e-01,
         1.00693281e-03],
       [ 1.25471181e+00, -8.26558256e-01,  8.96039649e-01,
        -1.10378108e+00]])

In [57]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [58]:
data[names=='Bob']

array([[-0.07345149, -1.06791298,  0.82147647, -0.13138896],
       [-0.35225029,  1.75681388, -0.19108014,  1.16667997]])

In [59]:
data[names=='Bob',2:]

array([[ 0.82147647, -0.13138896],
       [-0.19108014,  1.16667997]])

In [60]:
data[names=='Bob',3]

array([-0.13138896,  1.16667997])

In [61]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [64]:
data[~(names == 'Bob')]

array([[-0.73868458,  0.91962285, -0.36727474, -0.32371647],
       [ 1.74220837, -0.54183337,  2.42378349, -0.95671225],
       [ 0.4722768 ,  1.40820564, -0.3367378 ,  0.04394895],
       [ 0.20142736,  1.354718  , -1.03584902,  0.95023592],
       [-0.27605608, -1.40218439,  0.29593654, -0.47690992]])

In [66]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [67]:
data[mask]

array([[-0.07345149, -1.06791298,  0.82147647, -0.13138896],
       [ 1.74220837, -0.54183337,  2.42378349, -0.95671225],
       [-0.35225029,  1.75681388, -0.19108014,  1.16667997],
       [ 0.4722768 ,  1.40820564, -0.3367378 ,  0.04394895]])

In [68]:
# 将data中所有的负值设置为0
data[data<0] = 0
data

array([[0.        , 0.        , 0.82147647, 0.        ],
       [0.        , 0.91962285, 0.        , 0.        ],
       [1.74220837, 0.        , 2.42378349, 0.        ],
       [0.        , 1.75681388, 0.        , 1.16667997],
       [0.4722768 , 1.40820564, 0.        , 0.04394895],
       [0.20142736, 1.354718  , 0.        , 0.95023592],
       [0.        , 0.        , 0.29593654, 0.        ]])

In [69]:
data[names!='Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.91962285, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.20142736, 1.354718  , 0.        , 0.95023592],
       [0.        , 0.        , 0.29593654, 0.        ]])

In [70]:
# 花式索引
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [71]:
arr[[4,3,0,6]] # 以特定顺序选取行子集

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [72]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [74]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [75]:
arr[[1,5,7,2],[0,3,1,2]]  #(1,0) (5,3) ...

array([ 4, 23, 29, 10])

In [76]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [77]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [78]:
# 转置与轴对换
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [80]:
# 计算矩阵内积
arr = np.random.randn(6,3)
np.dot(arr.T, arr)

array([[ 4.47742757, -3.46078743,  0.79201549],
       [-3.46078743,  3.99098432, -1.34459549],
       [ 0.79201549, -1.34459549,  1.97426723]])

In [82]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [83]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [84]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [85]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])